name: "🚀 주요기능 개발"
description: "핵심 기능 단위의 이슈 정의"
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "기능 설명"
      description: "개발하려는 기능 설명"

  - type: textarea
    id: goal
    attributes:
      label: "기능 목표 / 기대 동작"
      description: "기능 상세 설명명"

  - type: textarea
    id: subtasks
    attributes:
      label: "필요한 서브기능들"
      description: "예상되는 작업 항목"
      placeholder: |
        - 예시시
        - [ ] GPIO 초기화
        - [ ] 상태 확인 함수
        - [ ] 명령 수신 처리

  - type: textarea
    id: notes
    attributes:
      label: "기타 참고사항"
      description: "메모, 참고 링크 등 자유롭게 작성"
