name: "\u2728 기능 제안"
description: 새로운 기능이나 개선점을 제안해주세요
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 현재 문제
      description: 제안하려는 기능이 해결하려는 문제를 설명해주세요.
      placeholder: 예: OBC 리셋 후 초기화 루틴이 누락됨
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 제안하는 해결 방법
      description: 기능 구현 아이디어나 구조를 설명해주세요.
      placeholder: 예: 초기화 태스크에서 리셋 상태 확인 후 RTC 재설정

  - type: textarea
    id: alternatives
    attributes:
      label: 고려했던 다른 방법
      description: 다른 접근 방식이 있다면 공유해주세요.

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 관련 문서, 링크, 참고할 내용 등이 있다면 여기에 작성해주세요.
